image: openjdk:11-jdk

stages:
  - compile
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

compile:
  stage: compile
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
